### PR TITLE
Fixing Issue 113 for Stable Version by changing API endpoint

### LINKED ISSUE #113: does not start, Stops at https://global.hoymiles.com/platform/api/gateway/pvm/station_select_device_all
Hi,

since today the Addon stopped working, also the edge Version. 
Tried already several reboots of HA and the addon.

It is starting to the line https://global.hoymiles.com/platform/api/gateway/pvm/station_select_device_all  and stops there. Same with the edge version. 

023-07-05 12:10:52,406 - HoymilesAdd-on - INFO - ********** dmslabs&Cosik Hoymiles Gateway  v.1.0.7
2023-07-05 12:10:52,406 - HoymilesAdd-on - INFO - Starting up... 2023-07-05 12:10:52
2023-07-05 12:10:52,407 - HoymilesAdd-on - INFO - Using Internal MQTT Server: core-mosquitto
2023-07-05 12:10:52,407 - HoymilesAdd-on - INFO - Using Internal MQTT User: addons
2023-07-05 12:10:52,408 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/iam/auth_login
2023-07-05 12:10:53,784 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - I got the token!!  :-)
2023-07-05 12:10:53,785 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm/station_find
2023-07-05 12:10:54,266 - HoymilesAdd-on.hoymilesapi.Hoymiles - INFO - Loading: https://global.hoymiles.com/platform/api/gateway/pvm/station_select_device_all

### PR DESCRIPTION
**Pull request by NikolasRupp**
Closes #113 by changing the API Endpont to "station_select_device_of_tree" instead of "station_select_device_all"

### CODE REVIEW

**Comment by Cosik** [comment]
Hi,

Please implement it to the edge instead of stable, second, you have to bump version, without it, it will not update without it.

**Comment by Cosik** [comment]
hoymiles.py need also version bump, and changes on stable should be reverted. When I come back, I will try to move edge to stable.

**Comment by Kwiatjk** [comment]
Dont working on EDGE 1.0.17

**Comment by NikolasRupp** [comment]
Oh sorry for that. Not really deep into git so please just send if something is wrong

**Comment by Kwiatjk** [comment]
Still no update on HACS

**Comment by ragman11** [comment]
How can we get the new Version?

**Comment by rehle65** [comment]
> How can we get the new Version?
It just needs a little bit of patience. The developers are doing this in their spare time. Maybe if you give a Cup of Coffee or two update will happen faster 😀

**Comment by Cosik** [comment]
Hi, finally I get access to my PC. I tested solution and it seems to work.

**Comment by ragman11** [comment]
Hi, thank you, edge Version works , all Hoymilesdata are back again.

**Comment by rehle65** [comment]
Thank you so much. All working fine

**Pull request merged**
