### PR TITLE
Fix meter values

### PR DESCRIPTION
**Pull request by xezpeleta**
Fix issue #154

### CODE REVIEW

**Comment by Cosik** [comment]
This has big impact on whole addon. Did you check how it behave?

**Comment by xezpeleta** [comment]
I can confirm I'm using the patched version and everything works well:

image


image


image

Thanks

**Comment by xezpeleta** [comment]
The other values seem to be ok

**Comment by Cosik** [comment]
This PR is using different requests than original addon. Changes are breaking so PR is closed

**Pull request closed without merging**
