### PR TITLE
Fix config json for Edge

### PR DESCRIPTION
**Pull request by Cosik**
Sorry I forget to change config.json. Also I made some small changes in md files.

### CODE REVIEW

**Comment by dmslabsbr** [comment]
I accept pull request. And I changed some text.  Could you check again if it is show good.

I also create a new folder, Stable, where we could put stable versions files.
In future we could remove the oldstable folder.
What do you think about it?

**Comment by Cosik** [comment]
Perfect work, thanks :)

**Comment by Cosik** [comment]
@dmslabsbr  something is wrong. Version 1.0 was put to stable version. Did I mess something?

**Comment by dmslabsbr** [comment]
@Cosik , I did'nt understand.  

1- The Old Stable Version Old Stable figure. folder /oldStable - We won't change anymore.
2 - The Edge Version Edge figure  /edge  -  Last updates. It may be unstable, but users using it help us to fix bugs. When we think a version is mature, we copy it to the stable folder.
3 - The Stable Version /stable - Stable versions. For users who don't want new bugs coming from new features.

I tested the latest version 1.0 that you sent "pull request" , but there was a problem. The "jsons" folder was not copied to the installed add-on.

So, I changed the run.sh file to force the necessary files copy.

**Comment by Cosik** [comment]
Ok, thanks. We could close it ;)

**Pull request merged**
